---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "oauth_test1"
          id: "oauth_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/oauth"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABC==)"
                tenant: "default"
              id: 2
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_refresh_token"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHI==)"
                tenant: "default"
              id: 3
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_access_token"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(MTY2ODY4NDI3OTE2Mw==)"
                tenant: "default"
              id: 4
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_expire_date"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(MA==)"
                tenant: "default"
              id: 5
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_refresh_flag"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGH=)"
                tenant: "default"
              id: 6
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_redirect_uri"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJK)"
                tenant: "default"
              id: 7
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_client_id"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(ABCDEFGHIJKLMNOPQRSTUVWXYZ+0123456789ABCDEFGHIJKLMNOPQ==)"
                tenant: "default"
              id: 8
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_client_secret"
            - options:
                environment: "test"
                encrypt: false
                modifier: "ComponentsTests/GetVariable"
                operation: "SET"
                value: "RAW(aHR0cHM6Ly9kZXZlbG9wbWVudC5kb3ZldGFpbC53b3JsZC9vYXV0aDJ0b2tlbi90ZXN0LzIwZjQ0Y2IwLTNk)"
                tenant: "default"
              id: 9
              type: "action"
              uri: "globalvariables://oauth2_20f44cb0-3d76-11ed-b962-0978946afb23_scope"
            - options:
                expiryDelay: 30
                tokenName: "OAuth2Token"
                id: "20f44cb0-3d76-11ed-b962-0978946afb23"
                tenant: "default"
              id: 10
              type: "action"
              uri: "oauth2token"
            - id: 11
              type: "sink"
              uri: "velocity:${header.OAuth2Token}"
