---
dil:
  core:
    messages:
      message:
        headers:
          firstname:
            language: "simple"
            type: "header"
            content: "${body}"
          lastname:
            language: "constant"
            type: "header"
            content: "Doe"
        name: "names"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "setheaders_test1"
          id: "setheaders_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/setheaders"
            - id: 2
              type: "action"
              uri: "setbody:john"
            - id: 3
              type: "action"
              uri: "setheaders:message:names"
            - id: 4
              type: "sink"
              uri: "velocity:The body is ${body}. The name is ${header.firstname}\
                \ ${header.lastname}"
