---
dil:
  core:
    messages:
      message:
        headers:
          home:
            language: "groovy"
            type: "header"
            content: "System.getProperty(\"user.home\")"
        name: "home"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "file_test1"
          id: "file_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/file"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 22
                  transport: "sync"
              id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<persons>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t<name>John Doe</name>\t\
                  \t\t\t\t\t\t  </person>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t\
                  <name>Jane Doe</name>\t\t\t\t\t\t\t  </person>\t\t\t\t\t\t\t</persons>"
            - links:
                link:
                - bound: "in"
                  id: 22
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 22
              type: "action"
              uri: "setheaders:message:home"
            - links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "file:${header.home}"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:Message Body: ${bodyAs(String)}"
