---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "xmltoedi_test1"
          id: "xmltoedi_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/xmltoedi"
            - id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<edi-message>  <delimiters segment=\"LB\" field=\"~\" component=\"\
                  ^\" sub-component=\"!\" />  <CUS>    <field.1>      <component.1>John</component.1>\
                  \      <component.2>Doe</component.2>    </field.1>    <field.2>1901-01-07</field.2>\
                  \    <field.3>john.doe@example.com</field.3>  </CUS></edi-message>"
            - id: 3
              type: "action"
              uri: "xmltoedi"
            - id: 4
              type: "sink"
              uri: "velocity:${bodyAs(String)}"
