---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "contentrouter_test1"
          id: "contentrouter_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/contentrouter"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<persons>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t<name>John Not\
                  \ Doe</name>\t\t\t\t\t\t\t  </person>\t\t\t\t\t\t\t  <person>\t\t\
                  \t\t\t\t\t\t<name>Blabla Doe</name>\t\t\t\t\t\t\t  </person>\t\t\
                  \t\t\t\t\t</persons>"
            - links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - expression: "/persons/person[1]/name='John Doe'"
                  bound: "out"
                  rule: "xpath"
                  id: 4
                  transport: "sync"
                - expression: "${body.contains('Jane')}"
                  bound: "out"
                  rule: "simple"
                  id: 5
                  transport: "sync"
                - bound: "out"
                  id: 6
                  transport: "sync"
              id: 3
              type: "router"
              uri: "content"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:Rule 1: ${bodyAs(String)}"
            - links:
                link:
                  bound: "in"
                  id: 5
                  transport: "sync"
              id: 5
              type: "sink"
              uri: "velocity:Rule 2: ${bodyAs(String)}"
            - links:
                link:
                  bound: "in"
                  id: 6
                  transport: "sync"
              id: 6
              type: "sink"
              uri: "velocity:Rule 3: ${bodyAs(String)}"
