---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "http_test1"
          id: "http_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/httpoutbound"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "log"
            - options:
                throwExceptionOnFailure: true
                maxTotalConnections: 20
                userAgent: "Dovetail/4.12.0"
                connectionsPerRoute: 2
                httpMethod: "GET"
                cookieStore: "#flowCookieStore"
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "http://www.testingmcafeesites.com/testcat_al.html"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:Message Body: ${bodyAs(String)}"
