---
dil:
  core:
    messages:
      message:
        headers:
          path:
            language: "groovy"
            type: "header"
            content: "System.getProperty(\"user.home\")"
        name: "names"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "exceltoxml_test1"
          id: "exceltoxml_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/exceltoxml"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setheaders:message:names"
            - links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "pollenrich:file://${header.path}?fileName=simplesheet2.xlsx&delete=false&noop=true"
            - links:
                link:
                - bound: "in"
                  id: 4
                  transport: "sync"
                - bound: "out"
                  id: 5
                  transport: "sync"
              id: 4
              type: "action"
              uri: "log"
            - options:
                rules: "RAW(WyJ7XCJjZWxsUmFuZ2VcIjpcIkExOkE0XCIsXCJkaXNjYXJkRW1wdHlcIjpmYWxzZSxcImhlYWRlclJvd1wiOmZhbHNlLFwibmFtZVwiOlwibmFtZXNcIixcInRyYW5zcG9zZVwiOmZhbHNlLFwid29ya3NoZWV0XCI6XCJTaGVldDFcIn0iXQ==)"
              links:
                link:
                - bound: "in"
                  id: 5
                  transport: "sync"
                - bound: "out"
                  id: 6
                  transport: "sync"
              id: 5
              type: "action"
              uri: "exceltoxml"
            - links:
                link:
                  bound: "in"
                  id: 6
                  transport: "sync"
              id: 6
              type: "sink"
              uri: "velocity:Message Body: ${bodyAs(String)}"
