---
dil:
  core:
    messages:
      message:
        headers:
          path:
            language: "groovy"
            type: "header"
            content: "System.getProperty(\"user.home\")"
        name: "userhome"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "pdftotext_test1"
          id: "pdftotext_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/pdftotext"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setheaders:message:userhome"
            - options:
                idempotent: false
                noop: true
                fileName: "test.pdf"
                synchronous: true
                delete: false
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: "3b"
                  transport: "sync"
              id: 3
              type: "action"
              uri: "pollenrich:file://C:\\Users\\Raymond"
            - links:
                link:
                - bound: "in"
                  id: "3b"
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: "3b"
              type: "action"
              uri: "log"
            - links:
                link:
                - bound: "in"
                  id: 4
                  transport: "sync"
                - bound: "out"
                  id: 5
                  transport: "sync"
              id: 4
              type: "action"
              uri: "pdftotext:id"
            - links:
                link:
                  bound: "in"
                  id: 5
                  transport: "sync"
              id: 5
              type: "sink"
              uri: "velocity:Message Body: ${bodyAs(String)}"
