---
dil:
  core:
    messages:
      message:
        headers:
          firstname:
            language: "constant"
            type: "header"
            content: "John"
          lastname:
            language: "constant"
            type: "header"
            content: "Doe"
        name: "removeheaders"
        id: 1
        body: "headers has been removed"
  integrations:
    integration:
      flows:
        flow:
          name: "removeheaders_test1"
          id: "removeheaders_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/removeheaders"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setmessage:message:removeheaders"
            - options:
                excludePattern: "breadcrumbId"
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "removeheaders:Lastname"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:Headers:Lastname: ${headers.lastName}Firtname:  ${headers.firstName}Message\
                \ Body:${bodyAs(String)}"
