---
dil:
  core:
    messages:
      message:
        headers:
          route:
            language: "constant"
            type: "header"
            content: "Mysql5.7"
          name:
            language: "constant"
            type: "header"
            content: "name"
          value:
            language: "constant"
            type: "header"
            content: "value"
          escape:
            language: "constant"
            type: "header"
            content: "no"
          timestamp:
            language: "simple"
            type: "header"
            content: "${date-with-timezone:now:Europe/Amsterdam:yyyy-MM-dd'T'HH:mm:ss}"
        name: "database"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "sql_test1"
          id: "sql_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/sql"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<persons>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t<name>John Doe</name>\t\
                  \t\t\t\t\t\t  </person>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t\
                  <name>Jane Doe</name>\t\t\t\t\t\t\t  </person>\t\t\t\t\t\t\t</persons>"
            - links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "setheaders:message:database"
            - options:
                password: "RAW(T25lVHdvMTI=)"
                database: "monitoring"
                tlsVersion: ""
                query: "RAW(U0VMRUNUIHZlcnNpb24oKQ==)"
                escapeChars: false
                connectionType: "mysql"
                useSSL: false
              links:
                link:
                - bound: "in"
                  id: 4
                  transport: "sync"
                - bound: "out"
                  id: 5
                  transport: "sync"
              id: 4
              type: "action"
              uri: "sql-custom://dovetail@monitoring.ch4wip2sipng.eu-west-1.rds.amazonaws.com:3306"
            - links:
                link:
                  bound: "in"
                  id: 5
                  transport: "sync"
              id: 5
              type: "sink"
              uri: "velocity:Message Body: ${bodyAs(String)}"
