---
dil:
  core:
    messages:
      message:
        name: "setcookie"
        id: 1
        body: "Cookie has been set"
  integrations:
    integration:
      flows:
        flow:
          name: "setcookie_test1"
          id: "setcookie_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/setcookie"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setmessage:message:setcookie"
            - options:
                name: "MyCookie"
                isSecure: false
                value: "MyCookie"
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "setcookie:org.assimbly"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:${bodyAs(String)}"
