---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "editoxml_test1"
          id: "editoxml_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/editoxml"
            - id: 2
              type: "action"
              uri: "setbody:CUS~John^Doe~1901-01-07~john.doe@example.com"
            - options:
                component: "^"
                field: "~"
                segment: "LB"
                subComponent: "!"
              id: 3
              type: "action"
              uri: "editoxml"
            - id: 4
              type: "sink"
              uri: "velocity:${bodyAs(String)}"
