---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "flowlink_inbound_test1"
          id: "flowlink_inbound_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/flowlink"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<persons>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t<name>John Doe</name>\t\
                  \t\t\t\t\t\t  </person>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t\
                  <name>Jane Doe</name>\t\t\t\t\t\t\t  </person>\t\t\t\t\t\t\t</persons>"
            - links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: "flowlink_4"
                  transport: "sync"
              id: 3
              type: "sink"
