---
dil:
  core:
    messages:
      message:
        headers:
          zip:
            language: "constant"
            type: "header"
            content: "10000, Alcochete"
          address:
            language: "constant"
            type: "header"
            content: "Main street 1"
          name:
            language: "constant"
            type: "header"
            content: "Pedro Catalao"
        name: "address"
        id: 1
  integrations:
    integration:
      flows:
        flow:
          name: "pdf_test1"
          id: "pdf_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/replaceinpdf"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setheaders:message:address"
            - options:
                uuid: "RAW(12345)"
                tenant: "RAW(tenant)"
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "replaceinpdf:http://localhost:9002/1/pdfs/flowid"
            - options:
                fileName: "result.pdf"
              links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "file:C:/data/pdf"
