---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "throttle_test1"
          id: "throttle_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/throttle"
            - id: 2
              type: "action"
              uri:
              - - "setbody:"
                - "<persons>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t<name>John Doe</name>\t\
                  \t\t\t\t\t\t  </person>\t\t\t\t\t\t\t  <person>\t\t\t\t\t\t\t\t\
                  <name>Jane Doe</name>\t\t\t\t\t\t\t  </person>\t\t\t\t\t\t\t</persons>"
            - links:
                link:
                  bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "log"
            - links:
                link:
                - bound: "in"
                  id: 4
                  transport: "sync"
                - expression: "/persons/person"
                  bound: "out"
                  rule: "xpath"
                  id: 5
                  transport: "sync"
                - bound: "out"
                  id: 8
                  transport: "sync"
              id: 4
              type: "router"
              uri: "split"
            - options:
                messages: 1
                timeperiod: 5000
              links:
                link:
                  bound: "in"
                  id: 5
                  transport: "sync"
              id: 5
              type: "action"
              uri: "throttle"
            - id: 6
              type: "action"
              uri: "log"
            - id: 7
              type: "sink"
              uri: "print:Message Body: ${bodyAs(String)}"
            - links:
                link:
                  bound: "in"
                  id: 8
                  transport: "sync"
              id: 8
              type: "sink"
              uri: "print:Default output"
