---
dil:
  core:
    messages:
      message:
        id: "flv"
        body: "YAYthing"
  integrations:
    integration:
      flows:
        flow:
          name: "flv_test1"
          id: "flv_test1"
          type: "esb"
          steps:
            step:
            - id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/Flv"
            - id: 2
              type: "action"
              uri: "setbody:message:flv"
            - options:
                YAY: "header[3]body[5]"
              id: 3
              type: "action"
              uri: "flv:2b611b10-d0f2-11ec-83f5-3747809ef661"
            - id: 4
              type: "sink"
              uri: "velocity:${bodyAs(String)}"
