---
dil:
  integrations:
    integration:
      flows:
        flow:
          name: "jsontoxml_test1"
          id: "jsontoxml_test1"
          type: "esb"
          steps:
            step:
            - links:
                link:
                  bound: "out"
                  id: 2
                  transport: "sync"
              id: 1
              type: "source"
              uri: "https://0.0.0.0:9001/1/jsontoxml"
            - links:
                link:
                - bound: "in"
                  id: 2
                  transport: "sync"
                - bound: "out"
                  id: 3
                  transport: "sync"
              id: 2
              type: "action"
              uri: "setbody:{  \"Formula1\": {    \"Drivers\": {      \"Driver\":\
                \ [        {          \"Age\": 19,          \"Name\": \"Max Verstappen\"\
                \        },        {          \"Age\": 30,          \"Name\": \"Nico\
                \ Hulkenberg\"        }      ]    },    \"Teams\": {      \"Team\"\
                : [        {          \"Principal\": \"Christian Horner\",       \
                \   \"Name\": \"Redbull Racing\"        },        {          \"Principal\"\
                : \"Carlos Ghosn, Jérôme Stoll, Cyril Abiteboul\",          \"Name\"\
                : \"Renault\"        }      ]    }  }}"
            - options:
                checkJsonKeys: false
                "false": false
                changeArrayElements: false
              links:
                link:
                - bound: "in"
                  id: 3
                  transport: "sync"
                - bound: "out"
                  id: 4
                  transport: "sync"
              id: 3
              type: "action"
              uri: "jsontoxml"
            - links:
                link:
                  bound: "in"
                  id: 4
                  transport: "sync"
              id: 4
              type: "sink"
              uri: "velocity:${bodyAs(String)}"
